<a href="https://colab.research.google.com/github/ibtihal7alharbi-tech/medical-cost-prediction/blob/main/ann_by_banan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras import regularizers
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.optimizers import Adam
import tensorflow.keras.backend as K

In [ ]:
df = pd.read_csv("/content/insurance.csv")
df
#Charges col is the target

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(1337, 7)

In [ ]:
# Text into numbers
le = LabelEncoder()

df['sex'] = le.fit_transform(df['sex'])       # male/female -> 1/0
df['smoker'] = le.fit_transform(df['smoker']) # yes/no -> 1/0
df['region'] = le.fit_transform(df['region']) # 4 regions -> 0,1,2,3

# drop the target col from X
X = df.drop('charges', axis=1)
y = df['charges']

df

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1337 rows x 7 columns]

In [ ]:
#Datasplitting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler_x = StandardScaler()
scaler_y = StandardScaler()

X_train = scaler_x.fit_transform(X_train)
X_test = scaler_x.transform(X_test)

y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1))
y_test_scaled = scaler_y.transform(y_test.values.reshape(-1, 1))

In [ ]:
X_train_fix = np.array(X_train).astype('float32')
y_train_fix = np.array(y_train).astype('float32')
X_test_fix = np.array(X_test).astype('float32')
y_test_fix = np.array(y_test).astype('float32')

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, r2_score
import numpy as np

scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(np.array(y_train).reshape(-1, 1)).astype('float32')
y_test_scaled = scaler_y.transform(np.array(y_test).reshape(-1, 1)).astype('float32')

#Build the model
model = Sequential([
    Dense(128, activation='relu', input_shape=(6,)),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dense(1)
])

#Compiling
model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

#Training:
print("Training on Scaled Data...")
model.fit(X_train_fix, y_train_scaled, validation_data=(X_test_fix, y_test_scaled),
          epochs=100, batch_size=32) # verbose=0 if I do not want the epoches to be shown

# 4. Predection + rewrite the original numbers
predictions_scaled = model.predict(X_test_fix)
predictions_final = scaler_y.inverse_transform(predictions_scaled)

# Final Evaluation
final_mae = mean_absolute_error(y_test, predictions_final)
final_r2 = r2_score(y_test, predictions_final)

print(f"MAE: {final_mae:.2f} $")
print(f"  (R2 Score): {final_r2 * 100:.2f}%")

Training on Scaled Data...
Epoch 1/100

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.5701 - mae: 0.5272 - val_loss: 0.2761 - val_mae: 0.3379
Epoch 2/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2549 - mae: 0.3435 - val_loss: 0.1827 - val_mae: 0.2522
Epoch 3/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2162 - mae: 0.3073 - val_loss: 0.1590 - val_mae: 0.2648
Epoch 4/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2043 - mae: 0.2971 - val_loss: 0.1522 - val_mae: 0.2530
Epoch 5/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1946 - mae: 0.2881 - val_loss: 0.1567 - val_mae: 0.2736
Epoch 6/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1771 - mae: 0.2740 - val_loss: 0.1532 - val_mae: 0.2624
Epoch 7/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1878 - mae: 0.2754 - val_loss: 0.1469 - val_mae: 0.2414
Epoch 8/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1807 - mae: 0.2698 - val_loss: 0.1547 - val_mae: 0.2592
Epoch 9/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1868 - mae: 0.2727 - val_loss: 0.1449 - val_mae: 0.2486
Epoch 10/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1727 - mae: 0.2668 - val_loss: 0.1453 - val_mae: 0.2396
Epoch 11/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1762 - mae: 0.2616 - val_loss: 0.1484 - val_mae: 0.2632
Epoch 12/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1761 - mae: 0.2670 - val_loss: 0.1472 - val_mae: 0.2513
Epoch 13/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1709 - mae: 0.2582 - val_loss: 0.1528 - val_mae: 0.2814
Epoch 14/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1749 - mae: 0.2604 - val_loss: 0.1478 - val_mae: 0.2718
Epoch 15/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1735 - mae: 0.2649 - val_loss: 0.1477 - val_mae: 0.2271
Epoch 16/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1761 - mae: 0.2597 - val_loss: 0.1467 - val_mae: 0.2554
Epoch 17/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1708 - mae: 0.2651 - val_loss: 0.1410 - val_mae: 0.2346
Epoch 18/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1700 - mae: 0.2597 - val_loss: 0.1381 - val_mae: 0.2311
Epoch 19/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1630 - mae: 0.2507 - val_loss: 0.1475 - val_mae: 0.2632
Epoch 20/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1661 - mae: 0.2501 - val_loss: 0.1459 - val_mae: 0.2607
Epoch 21/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1652 - mae: 0.2525 - val_loss: 0.1425 - val_mae: 0.2383
Epoch 22/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1679 - mae: 0.2540 - val_loss: 0.1446 - val_mae: 0.2326
Epoch 23/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1593 - mae: 0.2496 - val_loss: 0.1433 - val_mae: 0.2265
Epoch 24/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1599 - mae: 0.2471 - val_loss: 0.1390 - val_mae: 0.2529
Epoch 25/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1644 - mae: 0.2524 - val_loss: 0.1399 - val_mae: 0.2272
Epoch 26/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1568 - mae: 0.2430 - val_loss: 0.1575 - val_mae: 0.2475
Epoch 27/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1640 - mae: 0.2531 - val_loss: 0.1401 - val_mae: 0.2196
Epoch 28/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1563 - mae: 0.2447 - val_loss: 0.1383 - val_mae: 0.2244
Epoch 29/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1572 - mae: 0.2448 - val_loss: 0.1427 - val_mae: 0.2312
Epoch 30/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1539 - mae: 0.2372 - val_loss: 0.1382 - val_mae: 0.2329
Epoch 31/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1630 - mae: 0.2503 - val_loss: 0.1436 - val_mae: 0.2341
Epoch 32/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1532 - mae: 0.2407 - val_loss: 0.1446 - val_mae: 0.2210
Epoch 33/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1530 - mae: 0.2400 - val_loss: 0.1460 - val_mae: 0.2392
Epoch 34/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1520 - mae: 0.2373 - val_loss: 0.1423 - val_mae: 0.2268
Epoch 35/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1568 - mae: 0.2415 - val_loss: 0.1457 - val_mae: 0.2365
Epoch 36/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1561 - mae: 0.2429 - val_loss: 0.1465 - val_mae: 0.2347
Epoch 37/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1502 - mae: 0.2405 - val_loss: 0.1375 - val_mae: 0.2253
Epoch 38/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1481 - mae: 0.2344 - val_loss: 0.1437 - val_mae: 0.2456
Epoch 39/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1515 - mae: 0.2359 - val_loss: 0.1428 - val_mae: 0.2251
Epoch 40/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1495 - mae: 0.2413 - val_loss: 0.1424 - val_mae: 0.2377
Epoch 41/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1470 - mae: 0.2352 - val_loss: 0.1407 - val_mae: 0.2183
Epoch 42/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1434 - mae: 0.2334 - val_loss: 0.1421 - val_mae: 0.2253
Epoch 43/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1479 - mae: 0.2315 - val_loss: 0.1388 - val_mae: 0.2303
Epoch 44/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1459 - mae: 0.2298 - val_loss: 0.1423 - val_mae: 0.2374
Epoch 45/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1497 - mae: 0.2418 - val_loss: 0.1405 - val_mae: 0.2120
Epoch 46/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1479 - mae: 0.2337 - val_loss: 0.1490 - val_mae: 0.2575
Epoch 47/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1489 - mae: 0.2350 - val_loss: 0.1427 - val_mae: 0.2335
Epoch 48/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1451 - mae: 0.2351 - val_loss: 0.1408 - val_mae: 0.2132
Epoch 49/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1432 - mae: 0.2355 - val_loss: 0.1449 - val_mae: 0.2213
Epoch 50/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1488 - mae: 0.2357 - val_loss: 0.1406 - val_mae: 0.1987
Epoch 51/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1447 - mae: 0.2295 - val_loss: 0.1451 - val_mae: 0.2104
Epoch 52/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1461 - mae: 0.2354 - val_loss: 0.1425 - val_mae: 0.2357
Epoch 53/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1443 - mae: 0.2267 - val_loss: 0.1480 - val_mae: 0.2289
Epoch 54/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1440 - mae: 0.2344 - val_loss: 0.1440 - val_mae: 0.2132
Epoch 55/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1422 - mae: 0.2334 - val_loss: 0.1455 - val_mae: 0.2260
Epoch 56/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1413 - mae: 0.2315 - val_loss: 0.1580 - val_mae: 0.2257
Epoch 57/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1451 - mae: 0.2247 - val_loss: 0.1536 - val_mae: 0.2341
Epoch 58/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1410 - mae: 0.2308 - val_loss: 0.1426 - val_mae: 0.2275
Epoch 59/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1369 - mae: 0.2258 - val_loss: 0.1521 - val_mae: 0.2304
Epoch 60/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1407 - mae: 0.2293 - val_loss: 0.1519 - val_mae: 0.2168
Epoch 61/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1444 - mae: 0.2280 - val_loss: 0.1508 - val_mae: 0.2296
Epoch 62/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1382 - mae: 0.2273 - val_loss: 0.1424 - val_mae: 0.2058
Epoch 63/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1400 - mae: 0.2243 - val_loss: 0.1485 - val_mae: 0.2281
Epoch 64/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1362 - mae: 0.2246 - val_loss: 0.1443 - val_mae: 0.2222
Epoch 65/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1366 - mae: 0.2303 - val_loss: 0.1428 - val_mae: 0.2130
Epoch 66/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1400 - mae: 0.2238 - val_loss: 0.1490 - val_mae: 0.2257
Epoch 67/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1330 - mae: 0.2196 - val_loss: 0.1503 - val_mae: 0.2431
Epoch 68/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1358 - mae: 0.2294 - val_loss: 0.1472 - val_mae: 0.2442
Epoch 69/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1371 - mae: 0.2237 - val_loss: 0.1505 - val_mae: 0.2382
Epoch 70/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1392 - mae: 0.2277 - val_loss: 0.1460 - val_mae: 0.2299
Epoch 71/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1354 - mae: 0.2250 - val_loss: 0.1537 - val_mae: 0.2156
Epoch 72/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1411 - mae: 0.2282 - val_loss: 0.1460 - val_mae: 0.2291
Epoch 73/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1449 - mae: 0.2326 - val_loss: 0.1463 - val_mae: 0.2328
Epoch 74/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1327 - mae: 0.2159 - val_loss: 0.1628 - val_mae: 0.2301
Epoch 75/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1359 - mae: 0.2254 - val_loss: 0.1506 - val_mae: 0.2326
Epoch 76/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1355 - mae: 0.2248 - val_loss: 0.1527 - val_mae: 0.2397
Epoch 77/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1413 - mae: 0.2293 - val_loss: 0.1505 - val_mae: 0.2137
Epoch 78/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1312 - mae: 0.2144 - val_loss: 0.1493 - val_mae: 0.2422
Epoch 79/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1358 - mae: 0.2284 - val_loss: 0.1500 - val_mae: 0.2564
Epoch 80/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1326 - mae: 0.2256 - val_loss: 0.1514 - val_mae: 0.2389
Epoch 81/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1307 - mae: 0.2258 - val_loss: 0.1560 - val_mae: 0.2293
Epoch 82/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1316 - mae: 0.2197 - val_loss: 0.1472 - val_mae: 0.2138
Epoch 83/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1326 - mae: 0.2216 - val_loss: 0.1519 - val_mae: 0.2196
Epoch 84/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1354 - mae: 0.2206 - val_loss: 0.1572 - val_mae: 0.2331
Epoch 85/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1315 - mae: 0.2175 - val_loss: 0.1593 - val_mae: 0.2218
Epoch 86/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1324 - mae: 0.2252 - val_loss: 0.1511 - val_mae: 0.2300
Epoch 87/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1305 - mae: 0.2185 - val_loss: 0.1543 - val_mae: 0.2219
Epoch 88/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1342 - mae: 0.2268 - val_loss: 0.1551 - val_mae: 0.2288
Epoch 89/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1292 - mae: 0.2218 - val_loss: 0.1500 - val_mae: 0.2204
Epoch 90/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1331 - mae: 0.2158 - val_loss: 0.1540 - val_mae: 0.2219
Epoch 91/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1309 - mae: 0.2187 - val_loss: 0.1507 - val_mae: 0.2281
Epoch 92/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1282 - mae: 0.2162 - val_loss: 0.1528 - val_mae: 0.2368
Epoch 93/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1327 - mae: 0.2234 - val_loss: 0.1523 - val_mae: 0.2087
Epoch 94/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1300 - mae: 0.2203 - val_loss: 0.1517 - val_mae: 0.2111
Epoch 95/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1284 - mae: 0.2134 - val_loss: 0.1597 - val_mae: 0.2381
Epoch 96/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1253 - mae: 0.2181 - val_loss: 0.1566 - val_mae: 0.2181
Epoch 97/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1253 - mae: 0.2149 - val_loss: 0.1535 - val_mae: 0.2177
Epoch 98/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1306 - mae: 0.2178 - val_loss: 0.1572 - val_mae: 0.2363
Epoch 99/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1266 - mae: 0.2194 - val_loss: 0.1525 - val_mae: 0.2245
Epoch 100/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1280 - mae: 0.2202 - val_loss: 0.1574 - val_mae: 0.2158
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
MAE: 2525.30 $
  (R2 Score): 88.27%

In [ ]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                │ (None, 128)            │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 27,653 (108.02 KB)

 Trainable params: 9,217 (36.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 18,436 (72.02 KB)

"In the last period (Epoch 100), the model reached continuous stability, where the error in the training data and the test data were very close (around 0.21 in the adopted format). This persistence proves that the Regularization (such as Dropout and L2) that we used to prevent the models from saving data, became able to predict its knowledge to predict insurance prices for new people with an R2 accuracy of 88%."