<a href="https://colab.research.google.com/github/ibtihal7alharbi-tech/medical-cost-prediction/blob/main/Banan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras import regularizers
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.optimizers import Adam
import tensorflow.keras.backend as K
from sklearn.metrics import mean_absolute_error # Import mean_absolute_error

In [2]:
df = pd.read_csv("/content/insurance.csv")
df
#Charges col is the target

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
df.drop_duplicates(inplace=True)
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [4]:
# Text into numbers
le = LabelEncoder()

df['sex'] = le.fit_transform(df['sex'])       # male/female -> 1/0
df['smoker'] = le.fit_transform(df['smoker']) # yes/no -> 1/0
df['region'] = le.fit_transform(df['region']) # 4 regions -> 0,1,2,3

# drop the target col from X
X = df.drop('charges', axis=1)
y = df['charges']

df

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1337 rows x 7 columns]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler_x = StandardScaler()
scaler_y = StandardScaler()

X_train = scaler_x.fit_transform(X_train)
X_test = scaler_x.transform(X_test)

y_train_scaled = scaler_y.fit_transform(np.array(y_train).reshape(-1, 1)).astype('float32')
y_test_scaled = scaler_y.transform(np.array(y_test).reshape(-1, 1)).astype('float32')

In [6]:
def build_baseline_model(lr):
    model = keras.Sequential([
        keras.layers.Dense(128, activation="relu", input_shape=(6,)),
        keras.layers.Dense(64, activation="relu"),
        keras.layers.Dense(1) # Changed to 1 neuron with linear activation for regression
    ])

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=lr),
        loss="mse",
        metrics=["mae"]
    )
    return model

In [7]:
learning_rates = [0.1, 0.01, 0.001, 0.0001]

for lr in learning_rates:
    print(f"\nTraining with LR = {lr}")
    model = build_baseline_model(lr)
    model.fit(X_train, y_train_scaled, epochs=100, batch_size=32, verbose=0)
    loss, mae = model.evaluate(X_test, y_test_scaled, verbose=0)
    print(f"LR {lr} → mae: {mae:.4f}")

Training with LR = 0.1

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

LR 0.1 → mae: 0.2850

Training with LR = 0.01
LR 0.01 → mae: 0.2452

Training with LR = 0.001
LR 0.001 → mae: 0.2522

Training with LR = 0.0001
LR 0.0001 → mae: 0.2317

In [8]:
y_pred_scaled = model.predict(X_test)

y_pred_final = scaler_y.inverse_transform(y_pred_scaled).flatten()
y_true_final = y_test.values.flatten()

# $$$
mae_dollars = mean_absolute_error(y_true_final, y_pred_final)

#  MAPE
mape = np.mean(np.abs((y_true_final - y_pred_final) / y_true_final)) * 100

#  (Accuracy)
accuracy = 100 - mape

#
print("="*40)
print(f" (MAPE): {mape:.2f} %")
print(f"  (Accuracy): {accuracy:.2f} %")
print("="*40)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
========================================
 (MAPE): 30.33 %
  (Accuracy): 69.67 %
========================================

In [9]:
def evaluate_model_full(model, X_test_data, y_test_data, scaler_y_obj):
    y_pred_scaled = model.predict(X_test_data, verbose=0)

    y_pred_final = scaler_y_obj.inverse_transform(y_pred_scaled).flatten()
    y_true_final = y_test_data.values.flatten()


    mae_dollars = mean_absolute_error(y_true_final, y_pred_final)
    mape = np.mean(np.abs((y_true_final - y_pred_final) / y_true_final)) * 100
    accuracy = 100 - mape

    print("="*40)
    print(f"(MAE): {mae_dollars:.2f} $")
    print(f"(MAPE): {mape:.2f} %")
    print(f"(Accuracy): {accuracy:.2f} %")
    print("="*40)

In [10]:
#Tuning
def build_tuned_model():
    model = Sequential([
        Dense(256, activation='relu', input_shape=(6,)),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])
    return model

tuned_model = build_tuned_model()
tuned_model.fit(X_train, y_train_scaled, epochs=100, batch_size=32, verbose=0)

print("Tuning:")
evaluate_model_full(tuned_model, X_test, y_test, scaler_y)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Tuning:
========================================
(MAE): 3282.48 $
(MAPE): 46.31 %
(Accuracy): 53.69 %
========================================

In [11]:
#Dropout without tuning
def build_dropout_model():
    model = Sequential([
        Dense(128, activation='relu', input_shape=(6,)),
        Dropout(0.3),
        Dense(64, activation='relu'),
        Dropout(0.2),
        Dense(1)
    ])
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=lr),
        loss="mse",
        metrics=["mae"]
    )
    return model

dropout_model = build_dropout_model()
dropout_model.fit(X_train, y_train_scaled, epochs=100, batch_size=32, verbose=0)

print("Dropout:")
evaluate_model_full(dropout_model, X_test, y_test, scaler_y)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Dropout:
========================================
(MAE): 3056.54 $
(MAPE): 37.83 %
(Accuracy): 62.17 %
========================================

In [12]:
#dropout with tuning
def build_dropout1_model():
    model = Sequential([
        Dense(256, activation='relu', input_shape=(6,)),
        Dropout(0.3),
        Dense(128, activation='relu'),
        Dropout(0.2),
        Dense(1)
    ])
    model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])
    return model

dropout1_model = build_dropout1_model()
dropout1_model.fit(X_train, y_train_scaled, epochs=100, batch_size=32, verbose=0)

print("Dropout after tuning:")
evaluate_model_full(dropout1_model, X_test, y_test, scaler_y)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Dropout after tuning:
========================================
(MAE): 2553.76 $
(MAPE): 30.40 %
(Accuracy): 69.60 %
========================================

In [13]:
#L2:
from tensorflow.keras import regularizers

def build_l2_model():
    model = Sequential([
        Dense(256, activation='relu', input_shape=(6,), kernel_regularizer=regularizers.l2(0.01)),
        Dropout(0.3),
        Dense(128, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
        Dense(1)
    ])
    model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])
    return model

l2_model = build_l2_model()
l2_model.fit(X_train, y_train_scaled, epochs=100, batch_size=32, verbose=0)


print("L2:")
evaluate_model_full(l2_model, X_test, y_test, scaler_y)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

L2:
========================================
(MAE): 2826.72 $
(MAPE): 36.16 %
(Accuracy): 63.84 %
========================================

In [14]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor='val_loss', patience=30, restore_best_weights=True)
def build_final_early_model():
    model = Sequential([
        Dense(256, activation='relu', input_shape=(6,), kernel_regularizer=regularizers.l2(0.01)),
        Dropout(0.3),
        Dense(128, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
        Dense(1)
    ])
    model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])
    return model

final_model_es = build_final_early_model()

print("Training with Early Stopping...")
final_model_es.fit(
    X_train, y_train_scaled,
    validation_data=(X_test, y_test_scaled), # ضروري عشان يراقب الـ val_loss
    epochs=1000,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

print("\n⭐ نتائج الموديل مع Early Stopping:")
evaluate_model_full(final_model_es, X_test, y_test, scaler_y)

Training with Early Stopping...
Epoch 1/1000

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 1.9741 - mae: 0.4476 - val_loss: 1.4561 - val_mae: 0.2792
Epoch 2/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2480 - mae: 0.3018 - val_loss: 0.9933 - val_mae: 0.2598
Epoch 3/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8961 - mae: 0.2922 - val_loss: 0.7268 - val_mae: 0.2662
Epoch 4/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6774 - mae: 0.2820 - val_loss: 0.5845 - val_mae: 0.2506
Epoch 5/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5493 - mae: 0.2809 - val_loss: 0.4678 - val_mae: 0.2870
Epoch 6/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4547 - mae: 0.2855 - val_loss: 0.3864 - val_mae: 0.2321
Epoch 7/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4001 - mae: 0.2701 - val_loss: 0.3478 - val_mae: 0.2862
Epoch 8/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3496 - mae: 0.2744 - val_loss: 0.3098 - val_mae: 0.2604
Epoch 9/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3178 - mae: 0.2668 - val_loss: 0.2816 - val_mae: 0.2446
Epoch 10/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3025 - mae: 0.2742 - val_loss: 0.2555 - val_mae: 0.2617
Epoch 11/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2796 - mae: 0.2657 - val_loss: 0.2391 - val_mae: 0.2373
Epoch 12/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2681 - mae: 0.2708 - val_loss: 0.2252 - val_mae: 0.2391
Epoch 13/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.2558 - mae: 0.2593 - val_loss: 0.2196 - val_mae: 0.2366
Epoch 14/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2499 - mae: 0.2670 - val_loss: 0.2205 - val_mae: 0.2361
Epoch 15/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2361 - mae: 0.2588 - val_loss: 0.2038 - val_mae: 0.2379
Epoch 16/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2385 - mae: 0.2716 - val_loss: 0.2325 - val_mae: 0.2660
Epoch 17/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2329 - mae: 0.2599 - val_loss: 0.2175 - val_mae: 0.3119
Epoch 18/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2334 - mae: 0.2708 - val_loss: 0.2099 - val_mae: 0.2675
Epoch 19/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2271 - mae: 0.2644 - val_loss: 0.1915 - val_mae: 0.2546
Epoch 20/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2219 - mae: 0.2549 - val_loss: 0.1977 - val_mae: 0.2225
Epoch 21/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2232 - mae: 0.2540 - val_loss: 0.1885 - val_mae: 0.2612
Epoch 22/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2135 - mae: 0.2578 - val_loss: 0.1861 - val_mae: 0.2469
Epoch 23/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2203 - mae: 0.2615 - val_loss: 0.1870 - val_mae: 0.2549
Epoch 24/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2161 - mae: 0.2585 - val_loss: 0.1964 - val_mae: 0.2494
Epoch 25/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2116 - mae: 0.2543 - val_loss: 0.1863 - val_mae: 0.2487
Epoch 26/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2181 - mae: 0.2602 - val_loss: 0.1899 - val_mae: 0.2404
Epoch 27/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2141 - mae: 0.2559 - val_loss: 0.1826 - val_mae: 0.2349
Epoch 28/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2104 - mae: 0.2627 - val_loss: 0.1806 - val_mae: 0.2353
Epoch 29/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2076 - mae: 0.2511 - val_loss: 0.1824 - val_mae: 0.2221
Epoch 30/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2064 - mae: 0.2475 - val_loss: 0.1854 - val_mae: 0.2595
Epoch 31/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2087 - mae: 0.2503 - val_loss: 0.1841 - val_mae: 0.2697
Epoch 32/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2057 - mae: 0.2549 - val_loss: 0.1745 - val_mae: 0.2283
Epoch 33/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2127 - mae: 0.2583 - val_loss: 0.1911 - val_mae: 0.2886
Epoch 34/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2101 - mae: 0.2630 - val_loss: 0.1793 - val_mae: 0.2261
Epoch 35/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2067 - mae: 0.2499 - val_loss: 0.1866 - val_mae: 0.2965
Epoch 36/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2116 - mae: 0.2574 - val_loss: 0.1824 - val_mae: 0.2656
Epoch 37/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2072 - mae: 0.2660 - val_loss: 0.1768 - val_mae: 0.2067
Epoch 38/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2059 - mae: 0.2489 - val_loss: 0.1747 - val_mae: 0.2591
Epoch 39/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2031 - mae: 0.2499 - val_loss: 0.1753 - val_mae: 0.2392
Epoch 40/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2033 - mae: 0.2494 - val_loss: 0.1753 - val_mae: 0.2532
Epoch 41/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2109 - mae: 0.2558 - val_loss: 0.1832 - val_mae: 0.2385
Epoch 42/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2043 - mae: 0.2550 - val_loss: 0.1734 - val_mae: 0.2301
Epoch 43/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2037 - mae: 0.2516 - val_loss: 0.1763 - val_mae: 0.2531
Epoch 44/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2070 - mae: 0.2529 - val_loss: 0.1729 - val_mae: 0.2167
Epoch 45/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2155 - mae: 0.2578 - val_loss: 0.2065 - val_mae: 0.2507
Epoch 46/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2092 - mae: 0.2684 - val_loss: 0.1867 - val_mae: 0.2444
Epoch 47/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2010 - mae: 0.2483 - val_loss: 0.1716 - val_mae: 0.2043
Epoch 48/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2038 - mae: 0.2528 - val_loss: 0.1787 - val_mae: 0.2078
Epoch 49/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2019 - mae: 0.2524 - val_loss: 0.1793 - val_mae: 0.2225
Epoch 50/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2105 - mae: 0.2638 - val_loss: 0.1777 - val_mae: 0.2565
Epoch 51/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2017 - mae: 0.2464 - val_loss: 0.1693 - val_mae: 0.2360
Epoch 52/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2151 - mae: 0.2675 - val_loss: 0.1808 - val_mae: 0.2767
Epoch 53/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2025 - mae: 0.2490 - val_loss: 0.1687 - val_mae: 0.2371
Epoch 54/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2001 - mae: 0.2510 - val_loss: 0.1694 - val_mae: 0.1986
Epoch 55/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2045 - mae: 0.2516 - val_loss: 0.1814 - val_mae: 0.2734
Epoch 56/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2031 - mae: 0.2591 - val_loss: 0.1773 - val_mae: 0.2615
Epoch 57/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1989 - mae: 0.2531 - val_loss: 0.1756 - val_mae: 0.2578
Epoch 58/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2002 - mae: 0.2522 - val_loss: 0.1735 - val_mae: 0.2575
Epoch 59/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1969 - mae: 0.2419 - val_loss: 0.1771 - val_mae: 0.2825
Epoch 60/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1969 - mae: 0.2552 - val_loss: 0.1719 - val_mae: 0.2368
Epoch 61/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2015 - mae: 0.2535 - val_loss: 0.1644 - val_mae: 0.2116
Epoch 62/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2009 - mae: 0.2517 - val_loss: 0.1821 - val_mae: 0.2030
Epoch 63/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2034 - mae: 0.2492 - val_loss: 0.1824 - val_mae: 0.2943
Epoch 64/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1967 - mae: 0.2490 - val_loss: 0.1698 - val_mae: 0.2441
Epoch 65/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.2009 - mae: 0.2475 - val_loss: 0.1758 - val_mae: 0.2642
Epoch 66/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1994 - mae: 0.2497 - val_loss: 0.1766 - val_mae: 0.2410
Epoch 67/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1958 - mae: 0.2474 - val_loss: 0.1822 - val_mae: 0.2050
Epoch 68/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2014 - mae: 0.2548 - val_loss: 0.1828 - val_mae: 0.2679
Epoch 69/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1971 - mae: 0.2508 - val_loss: 0.1844 - val_mae: 0.2823
Epoch 70/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2004 - mae: 0.2516 - val_loss: 0.1729 - val_mae: 0.2538
Epoch 71/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2136 - mae: 0.2669 - val_loss: 0.1877 - val_mae: 0.1989
Epoch 72/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2076 - mae: 0.2598 - val_loss: 0.1729 - val_mae: 0.2349
Epoch 73/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1967 - mae: 0.2412 - val_loss: 0.1756 - val_mae: 0.2618
Epoch 74/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1993 - mae: 0.2537 - val_loss: 0.1741 - val_mae: 0.2721
Epoch 75/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2008 - mae: 0.2519 - val_loss: 0.1736 - val_mae: 0.2744
Epoch 76/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2030 - mae: 0.2613 - val_loss: 0.1704 - val_mae: 0.2171
Epoch 77/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2016 - mae: 0.2526 - val_loss: 0.1797 - val_mae: 0.2312
Epoch 78/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2019 - mae: 0.2578 - val_loss: 0.1725 - val_mae: 0.2626
Epoch 79/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1949 - mae: 0.2421 - val_loss: 0.1684 - val_mae: 0.2467
Epoch 80/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1960 - mae: 0.2532 - val_loss: 0.1655 - val_mae: 0.2366
Epoch 81/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1900 - mae: 0.2414 - val_loss: 0.1675 - val_mae: 0.2330
Epoch 82/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1955 - mae: 0.2482 - val_loss: 0.1642 - val_mae: 0.2174
Epoch 83/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2006 - mae: 0.2570 - val_loss: 0.1650 - val_mae: 0.2130
Epoch 84/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1927 - mae: 0.2451 - val_loss: 0.1643 - val_mae: 0.2330
Epoch 85/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1937 - mae: 0.2402 - val_loss: 0.1631 - val_mae: 0.2295
Epoch 86/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1983 - mae: 0.2475 - val_loss: 0.1644 - val_mae: 0.2418
Epoch 87/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2008 - mae: 0.2559 - val_loss: 0.1680 - val_mae: 0.2542
Epoch 88/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2000 - mae: 0.2541 - val_loss: 0.1634 - val_mae: 0.1962
Epoch 89/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1960 - mae: 0.2458 - val_loss: 0.1773 - val_mae: 0.2183
Epoch 90/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1923 - mae: 0.2367 - val_loss: 0.1800 - val_mae: 0.2884
Epoch 91/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1980 - mae: 0.2555 - val_loss: 0.1750 - val_mae: 0.2636
Epoch 92/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1940 - mae: 0.2507 - val_loss: 0.1663 - val_mae: 0.2308
Epoch 93/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2018 - mae: 0.2539 - val_loss: 0.1628 - val_mae: 0.2205
Epoch 94/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1912 - mae: 0.2450 - val_loss: 0.1741 - val_mae: 0.2156
Epoch 95/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1952 - mae: 0.2473 - val_loss: 0.1603 - val_mae: 0.2040
Epoch 96/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1899 - mae: 0.2449 - val_loss: 0.1614 - val_mae: 0.2167
Epoch 97/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1898 - mae: 0.2409 - val_loss: 0.1643 - val_mae: 0.2143
Epoch 98/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1982 - mae: 0.2549 - val_loss: 0.1618 - val_mae: 0.2036
Epoch 99/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1935 - mae: 0.2451 - val_loss: 0.1656 - val_mae: 0.2282
Epoch 100/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1924 - mae: 0.2433 - val_loss: 0.1637 - val_mae: 0.2399
Epoch 101/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1977 - mae: 0.2606 - val_loss: 0.1682 - val_mae: 0.2264
Epoch 102/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1975 - mae: 0.2419 - val_loss: 0.1678 - val_mae: 0.2547
Epoch 103/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1998 - mae: 0.2586 - val_loss: 0.1622 - val_mae: 0.2338
Epoch 104/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1959 - mae: 0.2399 - val_loss: 0.1692 - val_mae: 0.2183
Epoch 105/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1960 - mae: 0.2480 - val_loss: 0.1661 - val_mae: 0.2671
Epoch 106/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1939 - mae: 0.2396 - val_loss: 0.1753 - val_mae: 0.2805
Epoch 107/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1956 - mae: 0.2486 - val_loss: 0.1677 - val_mae: 0.2449
Epoch 108/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1958 - mae: 0.2568 - val_loss: 0.1772 - val_mae: 0.2634
Epoch 109/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2025 - mae: 0.2518 - val_loss: 0.1643 - val_mae: 0.1867
Epoch 110/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1907 - mae: 0.2444 - val_loss: 0.1618 - val_mae: 0.2369
Epoch 111/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1975 - mae: 0.2511 - val_loss: 0.1644 - val_mae: 0.2121
Epoch 112/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1874 - mae: 0.2387 - val_loss: 0.1628 - val_mae: 0.2216
Epoch 113/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1963 - mae: 0.2509 - val_loss: 0.1682 - val_mae: 0.2120
Epoch 114/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1967 - mae: 0.2433 - val_loss: 0.1622 - val_mae: 0.2339
Epoch 115/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.1936 - mae: 0.2410 - val_loss: 0.1839 - val_mae: 0.3121
Epoch 116/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2006 - mae: 0.2657 - val_loss: 0.1661 - val_mae: 0.2517
Epoch 117/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1910 - mae: 0.2460 - val_loss: 0.1827 - val_mae: 0.2169
Epoch 118/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1959 - mae: 0.2473 - val_loss: 0.1619 - val_mae: 0.2152
Epoch 119/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.1939 - mae: 0.2461 - val_loss: 0.1634 - val_mae: 0.2281
Epoch 120/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1883 - mae: 0.2441 - val_loss: 0.1763 - val_mae: 0.2836
Epoch 121/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1921 - mae: 0.2456 - val_loss: 0.1633 - val_mae: 0.2007
Epoch 122/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1921 - mae: 0.2354 - val_loss: 0.1721 - val_mae: 0.2828
Epoch 123/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1950 - mae: 0.2598 - val_loss: 0.1605 - val_mae: 0.2110
Epoch 124/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1884 - mae: 0.2390 - val_loss: 0.1697 - val_mae: 0.2558
Epoch 125/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1983 - mae: 0.2542 - val_loss: 0.1599 - val_mae: 0.1884
Epoch 126/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2068 - mae: 0.2584 - val_loss: 0.1626 - val_mae: 0.2260
Epoch 127/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1945 - mae: 0.2408 - val_loss: 0.1749 - val_mae: 0.2732
Epoch 128/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1899 - mae: 0.2473 - val_loss: 0.1839 - val_mae: 0.2120
Epoch 129/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1942 - mae: 0.2391 - val_loss: 0.1694 - val_mae: 0.2753
Epoch 130/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1964 - mae: 0.2578 - val_loss: 0.1614 - val_mae: 0.2057
Epoch 131/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1932 - mae: 0.2473 - val_loss: 0.1837 - val_mae: 0.2153
Epoch 132/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1885 - mae: 0.2430 - val_loss: 0.1705 - val_mae: 0.2461
Epoch 133/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2042 - mae: 0.2592 - val_loss: 0.1615 - val_mae: 0.1911
Epoch 134/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1944 - mae: 0.2498 - val_loss: 0.1692 - val_mae: 0.1844
Epoch 135/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1946 - mae: 0.2463 - val_loss: 0.1569 - val_mae: 0.1956
Epoch 136/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1891 - mae: 0.2425 - val_loss: 0.1591 - val_mae: 0.2297
Epoch 137/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1915 - mae: 0.2431 - val_loss: 0.1762 - val_mae: 0.2110
Epoch 138/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1886 - mae: 0.2458 - val_loss: 0.1800 - val_mae: 0.2177
Epoch 139/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1955 - mae: 0.2504 - val_loss: 0.1610 - val_mae: 0.2088
Epoch 140/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1905 - mae: 0.2382 - val_loss: 0.1688 - val_mae: 0.2498
Epoch 141/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1941 - mae: 0.2562 - val_loss: 0.1589 - val_mae: 0.1997
Epoch 142/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1946 - mae: 0.2498 - val_loss: 0.1617 - val_mae: 0.2297
Epoch 143/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1896 - mae: 0.2469 - val_loss: 0.1594 - val_mae: 0.2045
Epoch 144/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1921 - mae: 0.2443 - val_loss: 0.1645 - val_mae: 0.2593
Epoch 145/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.1919 - mae: 0.2458 - val_loss: 0.1589 - val_mae: 0.2027
Epoch 146/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1935 - mae: 0.2410 - val_loss: 0.1591 - val_mae: 0.2230
Epoch 147/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1906 - mae: 0.2535 - val_loss: 0.1594 - val_mae: 0.2253
Epoch 148/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1876 - mae: 0.2404 - val_loss: 0.1706 - val_mae: 0.2253
Epoch 149/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1870 - mae: 0.2418 - val_loss: 0.1670 - val_mae: 0.2633
Epoch 150/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1936 - mae: 0.2467 - val_loss: 0.1611 - val_mae: 0.2278
Epoch 151/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1898 - mae: 0.2444 - val_loss: 0.1696 - val_mae: 0.2161
Epoch 152/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1938 - mae: 0.2475 - val_loss: 0.1684 - val_mae: 0.2461
Epoch 153/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1923 - mae: 0.2443 - val_loss: 0.1567 - val_mae: 0.1985
Epoch 154/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1861 - mae: 0.2346 - val_loss: 0.1600 - val_mae: 0.2419
Epoch 155/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1952 - mae: 0.2465 - val_loss: 0.1575 - val_mae: 0.2405
Epoch 156/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1966 - mae: 0.2490 - val_loss: 0.1670 - val_mae: 0.2380
Epoch 157/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1866 - mae: 0.2527 - val_loss: 0.1580 - val_mae: 0.1838
Epoch 158/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1890 - mae: 0.2369 - val_loss: 0.1578 - val_mae: 0.2135
Epoch 159/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1869 - mae: 0.2465 - val_loss: 0.1808 - val_mae: 0.2396
Epoch 160/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1930 - mae: 0.2443 - val_loss: 0.1636 - val_mae: 0.2324
Epoch 161/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1933 - mae: 0.2409 - val_loss: 0.1641 - val_mae: 0.2378
Epoch 162/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1909 - mae: 0.2499 - val_loss: 0.1680 - val_mae: 0.2460
Epoch 163/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1932 - mae: 0.2414 - val_loss: 0.1612 - val_mae: 0.2183
Epoch 164/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1945 - mae: 0.2513 - val_loss: 0.1556 - val_mae: 0.1927
Epoch 165/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.1989 - mae: 0.2513 - val_loss: 0.1730 - val_mae: 0.2010
Epoch 166/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.1904 - mae: 0.2360 - val_loss: 0.1553 - val_mae: 0.2160
Epoch 167/1000
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.1870 - mae: 0.2436 - val_loss: 0.1605 - val_mae: 0.1966
Epoch 168/1000